default_context:
  project_name: 'BioPlateDeploy'
  project_slug: 'BioPlateDeploy'
  domain_main: 'plate.mfserver.net'
  backend_cors_origins: 'https://plate.mfserver.net'
  docker_swarm_stack_name_main: 'plate-mfserver-net'
  traefik_constraint_tag: 'plate.mfserver.net'
  traefik_public_network: 'traefik-public'
  traefik_public_constraint_tag: 'traefik-public'
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*]
  _template: ./
